Repository 1mingfei/KNN2, pull requests merged in 2020-02, with the labels that each got.

#28 Ediff options
  include/KNHome.h
  include/LSKMC.h
  include/gbCnf.h
  src/KMCSimulation.cpp
  src/KNBondCount.cpp
  src/KNEncodeCart.cpp
  src/KNParam.cpp
  src/LSKMC.cpp
  src/params_example/kmc.param.lskmc
Labels: bug, enhancement

#39 mpi version of NBL
  include/KNHome.h
  include/gbCnf.h
  src/KMCSimulation.cpp
  src/KNBondCount.cpp
  src/KNEncodeCart.cpp
  src/KNHome.cpp
  src/KNSolidSol.cpp
  src/findClusters.cpp
  src/gbInCnf.cpp
  src/neighbor.cpp
Labels: enhancement

#41 tmp update kMC
  include/KNHome.h
  include/gbCnf.h
  src/KMCSimulation.cpp
  src/KNBondCount.cpp
  src/KNEncodeCart.cpp
  src/LSKMC.cpp
  src/findClusters.cpp
  src/neighbor.cpp
Labels: Others

#42 Mpi kmc
  src/KMCSimulation.cpp
Labels: bug

#44 MPI for neighborlist for 2D array w/ contiguous memory
  Makefile.gl.omp
  include/KNHome.h
  include/KNUtility.h
  src/KMCSimulation.cpp
  src/neighbor.cpp
Labels: bug, enhancement

#46 merge mpi_KMC to master
  include/KMCEvent.h
  src/KMCEvent.cpp
  src/KMCSimulation.cpp
Labels: enhancement

#47 Find cluster output filename
  .gitignore
  src/findClusters.cpp
Labels: Others

#49 Find cluster output filename
  .gitignore
  include/KNHome.h
  src/KNHome.cpp
  src/KNMain.cpp
  src/KNParam.cpp
  src/findClusters.cpp
  src/params_example/kn.param.findclusters
Labels: enhancement

#52 give cluster id as the ranking of the cluster size
  src/findClusters.cpp
Labels: enhancement

#57 parallel LSKMC and some house keeping again
  include/LSKMC.h
  src/KMCSimulation.cpp
  src/LSKMC.cpp
Labels: enhancement

#60 push
  include/KNHome.h
  src/KNParam.cpp
Labels: bug

#64 correct header added
  Makefile
  include/OrderedStruct.h
  src/OrderedStruct.cpp
Labels: bug

#66 bug fix
  src/KNEncodeCart.cpp
Labels: bug
